### ISSUE TITLE
Web Version of the app

### ISSUE THREAD

**Issue by dnemesisd** [vikasdummy/kashmiriDictionaryIssueTracker#18]

**Comment by vikasdummy** [comment]
http://www.vogella.com/tutorials/Android/article.html#manifestdetails_package
http://developer.android.com/guide/topics/manifest/manifest-element.html

currently set as: 
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="org.bhairav.kashmiridictionary"
    android:versionCode="1"
    android:versionName="1.0.1" >

**Comment by dnemesisd** [comment]
?? why is it closed?

**Comment by vikasdummy** [comment]
jus version change
