### ISSUE TITLE
Alignment issues : width and position of the search box

### ISSUE THREAD

**Issue by dnemesisd** [vikasdummy/kashmiriDictionaryIssueTracker#19]
Fix the position and alignment

**Comment by dnemesisd** [comment]
search box should be device agnostic

**Comment by vikasdummy** [comment]
Dis the earlier versions also have default text inside search box mis aligned to wards top?

also is it only the default text mis aligned or user input text as well?

**Comment by dnemesisd** [comment]
no. the intial version has proper text inside and the one that was typed.
In this version both the default text and typed text are cut off from the top..

**Comment by dnemesisd** [comment]
make it dynamic..based on device size..there must be apk classes to do that

**Comment by dnemesisd** [comment]
help buttuon mis-alligned..raised a new bug too..you can close that one if u r tracking this issue here

**Comment by vikasdummy** [comment]
Will make search box also custom. Different devices show search box as per their own settings. Dont want that.
