### ISSUE TITLE
Amit  Sanjay idea: Two Way dictionary

### ISSUE THREAD

**Issue by dnemesisd** [vikasdummy/kashmiriDictionaryIssueTracker#20]
Currently the dictionary only provides  a Kashmiri word to English translation .
This will limit the number of users who have limited knowledge of Kashmiri.

A two way dictionary should be constructed (type in English and Kashmiri words should be displayed)

**Comment by vikasdummy** [comment]
This is a very important feature.
i thought about it and how we can create it from
current database. Limitation is memory.
it will quire another 4mb memory which looks bad
wrt an android app. So a seperate app will is better.

**Comment by dnemesisd** [comment]
additional 4 MB is not bad. but the problem is how will you find kashmir word for english.

Bcz kashmiri words have English meaning like a sentence. it is not a one to one co-relation.  (that is bcz kashmiri langauge is way advanced than English)

Unless you re-create a dictionary of english words corresponding to a kashmir word..

**Comment by dnemesisd** [comment]
having a separate app is not a good idea. Dictionary is supposed to be big..unless u have the dictionary database on the server and everytime do lookup of the words and retrieve the results

**Comment by dnemesisd** [comment]
i was thinking about 2 way search! From English to kashmiri would be very difficult..since kashmiri meaning have many words in english.. sometimes a full sentence is used to display the meaning of kashmiri word.

I am thinking of a possible approach (let me know if you have already have thought of something)
1. Create a English database
   http://www-01.sil.org/linguistics/wordlists/english/
2. Do a context text search
   http://docs.oracle.com/cd/B28359_01/text.111/b28303/query.htm#i1006528
3. have a score system and retrieve results with highest score..(or more than one)

so something like this:
- We already have the english words/sentences for kashmiri words
- mapping from kashmiri to English is a) One to one b) One to Many

So we have to take the many words in English and display a corresponding kashmiri word. so to do that. We take all the English words (see link above).. Assign each a number (if space issue) is a problem.

So here is what i propose (or similar like that)
1. Create a table with meanings for all kashmiri words in English (see pic)
![11](https://cloud.githubusercontent.com/assets/7094330/2636361/8d966312-be90-11e3-93e1-88a7191d6276.jpg)
1. So when someone searches a  word (in this case mandul) the corresponding Kashmiri word is displayed. if there are multiple matches then we show them all.  ( as below)
   ![12](https://cloud.githubusercontent.com/assets/7094330/2636370/a8b8a484-be90-11e3-8c41-e762852370f4.jpg)
2.  So if there a one to one to match dipslay that kashmiri word.
   For Kashmiri words that have full sentence as a meaning..We can do either two things:
   a). Give a score to words and this give words with higher score as displayed image
   b) or count number of occurrences. More the count higher the priority.

Let me know what you think

**Comment by vikasdummy** [comment]
> > So we have to take the many words in English and display a corresponding kashmiri word. so to do that. We take all the English words (see link above).
> > -- we will still need to save the mapping for number to word lookup. so space is still used.

**Comment by vikasdummy** [comment]
so i did some work on this .
i took some sans to eng words and used those 
to get the kash to sans to eng words. 
Results are good and narrow but the number of words ie english words is abt 2000.
Its not that good.

actually this can be accomplished manually :) but i dont have that much time to waste.
soo,,,
ill look at your sans db and see what can be done
main problem with it is that its not one to one. ie it dosent have a single eng word for a single sans word

# ...

UI part of this issue:
-- @dnemesisd I want a good ui.current sucks 
hmm will think over it.

**Comment by vikasdummy** [comment]
#50 
#51
