### ISSUE TITLE
Banti Didi : Increase font size

### ISSUE THREAD

**Issue by dnemesisd** [vikasdummy/kashmiriDictionaryIssueTracker#26]
increase font size.. too hard to read

**Comment by vikasdummy** [comment]
can u quantify? give me a screen shot.

**Comment by dnemesisd** [comment]
text size smaller on bigger screen.People who are elderly cannot see easily..

**Comment by vikasdummy** [comment]
is pinch zoom ok?(only for meaning) 
do u feel ki search box should also be big?(only for big screens?)

**Comment by vikasdummy** [comment]
pinch zoom not feasible over scroll view.

increased font size as of now. Better for bigger screens and old people.
But somehow it dose not look too good on my screen.(but good for old people) Lets see if i can add modes.
