### ISSUE TITLE
omesh: kashmir not searchable.

### ISSUE THREAD

**Issue by vikasdummy** [vikasdummy/kashmiriDictionaryIssueTracker#35]
should english spelling be supported, can we use LCS algorithm to
show suggest 4-5 results in case of nothing found.

**Comment by dnemesisd** [comment]
yes..english shd be supported..otherwise the user will think that the search is not correct

**Comment by vikasdummy** [comment]
hmm this one is really tricky ...
kashmeer or kashmir. Will have to change the "core sound to letter mapping".
We can do a brainstorm at most optimum mapping. :)

Objective should be: user should be able to go smoothly with this mapping.
Providing a brahmi script writer will also be awesome for mapping.
hmm..
but garbage in results in garbage out. 

If its only for one word Kashmir , we can hanle this word specially, as it deserves so :)

**Comment by vikasdummy** [comment]
we could group such specialized words together. :)
