### ISSUE TITLE
Release it on Google Play

### ISSUE THREAD

**Issue by vikasdummy** [vikasdummy/kashmiriDictionaryIssueTracker#36]
All must do for beta done. !!!!!!!!!! claps claps
Lets relese it.

-- code log removals
-- trimming of data
-- deployment process at play store.

**Comment by vikasdummy** [comment]
fking ggle wallet. :X

**Comment by dnemesisd** [comment]
Good job Vicky! You did it..app looks good..Lets spread the word now..that is also important..

**Comment by vikasdummy** [comment]
i want a tab screen shot? kindle sae hoga? if its rooted , shouldnt be hard!?

**Comment by vikasdummy** [comment]
4 things for new release:
1.  change font of e to k data
2.  dont enable pattern for e to k in reverse mode. show message.
3.  update help data for new danasyir
4. change test parameters and version id 

GO GO GO govinda :dancer:
