### ISSUE TITLE
Issue: Unreadable characters []

### ISSUE THREAD

**Issue by dnemesisd** [vikasdummy/kashmiriDictionaryIssueTracker#6]
Device : Amazon Kindle
Some characters do not appear in readable format. See pic
![photo](https://cloud.githubusercontent.com/assets/7094330/2552473/c902ff36-b699-11e3-9038-d8c7f104dcbc.JPG)

**Comment by vikasdummy** [comment]
references: http://stackoverflow.com/questions/15608520/how-to-get-hindi-fonts-in-android

**Comment by dnemesisd** [comment]
Working now!
