### ISSUE TITLE
Search issue 

### ISSUE THREAD

**Issue by dnemesisd** [vikasdummy/kashmiriDictionaryIssueTracker#7]
![photo 1](https://cloud.githubusercontent.com/assets/7094330/2552602/d076667a-b69b-11e3-8be6-e4bd2b85c774.JPG)
How would a user search for some words which have symbols not present on the keyboard. e.g Chokuju in the screen shot

Possible solution : if i enter "O" it should give the user all possible searches for "O" 

Search has to be loose to give probable matches.. (Intelligent search)

**Comment by vikasdummy** [comment]
there is a mapping. not shown yet to use but will be added as usage info later.
fyi:

LEGEND of special symbols:

symbol|example_english|example_devnagri|search_usage
_a|ts_aha|च.ह|you|[n.w.]
_ȧ|ạnd_ȧri|अंन्दरि|inside|[n.w.]
a|krakh|क्रख|scream|a
ā|karā|करा आ|should I do it?|a
ạ|ạdarun|आ दरून|to get wet|a
ȧ|ȧsi|आ सि|we|aa
ā|ṭhākur|ठाकुर|lord|a
ai|rŏpai|रोपाइ|rupee|ai
au|karyōn|कर्योन्|cause|au
_ĕ|bạñĕrāwun|बञ््रावुन्|to make|[n.w.]
ĕ|bĕñĕ|ब्यन|sister|ey
ẹ̆|vẹ̆thun|व्यठुन|fatten|ey
ë˘|të˘thü|टयोठ |bitter|eo
ē|mēl|मेल्|meet|ai
_i|myöni|म्यानि|mine|i
i|nishĕ|निश|near|i
ī|shīn|शीन्|ice|ee
_o|d_onu|द् नु ्|shake|[n.w.]
ŏ|dŏd|द्वद्|milk|vo
ọ̆|gọ̆nu|ग्‍वनु|stack|vo
ŏ̈|ʦhŏ̈pü|छ़्व पू|wodden device to clean rice|ou
o|boḍu|बुडु|great|o
ō|pōsh|पोश्|flower|o
ô|môl|मोल|father|oo
ö|ös|आस्|mouth|ou
_u|boḍu|बडु|great|u
u|kus|कुस्|who|u
ū|ʦūr|चूर|thief|oo
_ü|kür_ün|करून्|doing|u
ü|büḍü|बडू|great|u
ṻ|sṻty|सूत्य्|with|ou
ḍ|ḍĕji|ड्यजि|cloth mass|d
ñ|añĕgoṭu|अञगटु|darkness|n
ṭ|gāṭulu|गाटुलु‍|wise|t
ʦ|gaʦhun|गछुन्|to go|ts

**Comment by vikasdummy** [comment]
search can use '?' to do smart search as wild card, will implement that.
for example w?ngun will give wangun and likes.

**Comment by dnemesisd** [comment]
Yes.. Use wild card (?)

**Comment by dnemesisd** [comment]
actually i meant if you search like this:

wa... ngun.. so when you type wa..it should give all matches of wa (with symbols above below)

it should not retreve words with w and m..

so wild card only with same character..i hope I was able to make it clear

**Comment by vikasdummy** [comment]
not clear.

**Comment by vikasdummy** [comment]
added support for ? wild card.
