### ISSUE TITLE
Enhancement : Make the app look pretty :)

### ISSUE THREAD

**Issue by dnemesisd** [vikasdummy/kashmiriDictionaryIssueTracker#9]
See screen shot. may be add "word of the day" when someone opens the app with meaning already added to it.

![photo](https://cloud.githubusercontent.com/assets/7094330/2552712/34beb29e-b69d-11e3-95ec-5ecf153e148c.PNG)

**Comment by vikasdummy** [comment]
Oh wow. This looks nice !
Some layout changes and colours can do magick ;)

**Comment by vikasdummy** [comment]
http://angrytools.com/android/button/

**Comment by vikasdummy** [comment]
This color looks awesome. Will copy it.

**Comment by vikasdummy** [comment]
Check the duolingo
It is wonderful UI
